authapp/urls.py
from django.urls import path
from authapp import views as authapp

app_name = 'authapp'


urlpatterns = [
    path('login/', authapp.LoginView.as_view(), name='login'),
    path('logout/', authapp.LogoutView.as_view(), name='logout'),
    path('register/', authapp.RegisterView.as_view(), name='register'),
    path('edit/', authapp.EditView.as_view(), name='edit'),
    path('users/', authapp.UserListView.as_view(), name='users_list'),
    path('user/create/', authapp.UserCreateView.as_view(), name='user_create'),
    path('user/update/<int:pk>/', authapp.UserUpdateView.as_view(),
         name='user_update'),
    path('user/delete/<int:pk>/', authapp.UserDeleteView.as_view(),
         name='user_delete'),

    path('api/user_create/', authapp.UserCreateAPIView.as_view(), name='api_user_create'),
    path('api/user_update/<int:pk>/', authapp.UserUpdateAPIView.as_view(), name='api_user_update'),
]

bookapp/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from bookapp import views as bookapp

app_name = 'bookapp'

urlpatterns = [
    path('book_create/', bookapp.BookCreateView.as_view(), name='book_create'),
    path('book_read/<pk>/', bookapp.BookDetailView.as_view(), name='book_read'),
    path('book_update/<pk>/', bookapp.BookUpdateView.as_view(), name='book_update'),
    path('book_delete/<pk>/', bookapp.BookDeleteView.as_view(), name='book_delete'),

    path('api/books_create/', bookapp.BookCreateAPIView.as_view(), name='books_create_api'),
    path('api/books_update/<int:pk>/', bookapp.BookUpdateAPIView.as_view(), name='books_update_api'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bookshelf/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from mainapp import views as mainapp

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('books/', include('bookapp.urls', namespace='books')),
    path('', mainapp.Index.as_view(), name='index'),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mainapp/models.py
from django.db import models

# Create your models here.

mainapp/views.py
from django.views.generic import ListView
from bookapp.models import Books


class Index(ListView):
    """Главная страница"""
    context_object_name = "books"
    paginate_by = 6
    template_name = 'mainapp/index.html'

    def get_queryset(self):
        return Books.objects.all().order_by('-created_at')

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Главная'
        return context

templates/mainapp/index.html
{% extends 'base.html' %}
{% load static %}
{% load media_tags %}

{% block content %}
    {% if user.is_authenticated %}
        <a class="nav-item nav-link navigation-links add_button" href="{% url 'books:book_create' %}"><i
                class="fa fa-plus"></i>
            Добавить книгу
        </a>
    {% endif %}
    <div class="books_block">
        {% for book in books %}
            <div class="container_box">
                <div class="index_book_img_box">
                    <img class="book_img" src="{{ book.image|media_for_books }}" alt="book_img"/>
                </div>

                <div class="book_info">
                    <h3>{{ book.name }}</h3>
                    Автор: {{ book.user.first_name }} {{ book.user.patronymic }} {{ book.user.last_name }}
                                    <div>
                    <a href="{% url 'books:book_read' book.id %}"
                       class="btn btn-success">читать</a>
                    {% if user.id == book.user.id or user.is_superuser %}
                        <a href="{% url 'books:book_update' book.id %}"
                           class="btn btn-warning">редактировать</a>
                    {% endif %}
                </div>
                </div>

            </div>
        {% endfor %}
    </div>
    <div class="pagi_div">
        <nav>
            {% if is_paginated %}
                <ul class="pagination">
                    {% if page_obj.has_previous %}
                        <li class="page-item">
                            <a class="page-link" href="?page={{ page_obj.previous_page_number }}">&laquo;</a>
                        </li>
                    {% else %}
                        <li class="page-item disabled">
                            <a class="page-link" href="#">&laquo;</a>
                        </li>
                    {% endif %} {% for i in paginator.page_range %} {% if page_obj.number == i %}
                    <li class="page-item"><a class="page-link active">{{ i }}</a></li>
                {% else %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ i }}">{{ i }}</a>
                    </li>
                {% endif %} {% endfor %} {% if page_obj.has_next %}
                    <li class="page-item">
                        <a href="?page={{ page_obj.next_page_number }}" class="page-link">&raquo;</a>
                    </li>
                {% else %}
                    <li class="page-item disabled">
                        <a class="page-link">&raquo;</a>
                    </li>
                {% endif %}
                </ul>
            {% endif %}
        </nav>
    </div>
{% endblock %}