authapp/urls.py
from django.urls import path
from authapp import views as authapp

app_name = 'authapp'


urlpatterns = [
    path('login/', authapp.LoginView.as_view(), name='login'),
    path('logout/', authapp.LogoutView.as_view(), name='logout'),
    path('register/', authapp.RegisterView.as_view(), name='register'),
    path('edit/', authapp.EditView.as_view(), name='edit'),
    path('users/', authapp.UserListView.as_view(), name='users_list'),
    path('user/create/', authapp.UserCreateView.as_view(), name='user_create'),
    path('user/update/<int:pk>/', authapp.UserUpdateView.as_view(),
         name='user_update'),
    path('user/delete/<int:pk>/', authapp.UserDeleteView.as_view(),
         name='user_delete'),

    path('api/user_create/', authapp.UserCreateAPIView.as_view(), name='api_user_create'),
    path('api/user_update/<int:pk>/', authapp.UserUpdateAPIView.as_view(), name='api_user_update'),
]

bookshelf/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from mainapp import views as mainapp

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('books/', include('bookapp.urls', namespace='books')),
    path('', mainapp.Index.as_view(), name='index'),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

authapp/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from phonenumber_field.modelfields import PhoneNumberField

NULLABLE = {'blank': True, 'null': True}


class User(AbstractUser):
    """Профиль пользователя"""
    avatar = models.ImageField(upload_to='users_avatars', verbose_name='Аватар', **NULLABLE)
    age = models.PositiveSmallIntegerField(verbose_name='Возраст', **NULLABLE)
    patronymic = models.CharField(max_length=150, verbose_name='Отчество', **NULLABLE)
    phone = PhoneNumberField(verbose_name='Номер телефона', **NULLABLE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

authapp/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, UserChangeForm
from authapp.models import User


class UserLoginForm(AuthenticationForm):
    class Meta:
        model = User
        fields = ('username', 'password')

    def __init__(self, *args, **kwargs):
        super(UserLoginForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''


class UserRegisterForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'patronymic', 'phone',
                  'avatar', 'email', 'age', 'password1', 'password2')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''

    def save(self, *args, **kwargs):
        user = super().save(*args, **kwargs)
        user.is_active = True
        user.save()
        return user


class UserEditForm(UserChangeForm):
    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'patronymic', 'phone',
                  'avatar', 'email', 'age')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''
            if field_name == 'password':
                field.widget = forms.HiddenInput()

authapp/views.py
from django.contrib import auth
from django.http import Http404
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse, reverse_lazy
from django.views.generic import ListView, CreateView, DeleteView, UpdateView
from django.views.generic import View
from rest_framework import status
from rest_framework.response import Response
from rest_framework.views import APIView
from authapp.forms import UserLoginForm, UserRegisterForm, UserEditForm
from authapp.models import User
from authapp.serializers import UserSerializer
from mainapp.mixins import SuperUserCheck, BelongsToUserCheck


# class AccessMixin:
#     """Делает view доступным только для суперпользователя"""
#
#     @method_decorator(user_passes_test(lambda u: u.is_superuser))
#     def dispatch(self, request, *args, **kwargs):
#         return super().dispatch(request, *args, **kwargs)


class LoginView(View):
    """Страница логина"""
    model = User
    template_name = 'authapp/user_auth/login.html'
    form_class = UserLoginForm

    def get(self, request):
        form = self.form_class()
        return render(request, self.template_name, context={'form': form,
                                                            'title': 'Логин'})

    def post(self, request):
        username = request.POST['username']
        password = request.POST['password']
        user = auth.authenticate(username=username, password=password)
        if user:
            auth.login(request, user)
            return HttpResponseRedirect(reverse('index'))
        form = self.form_class()
        return render(request, self.template_name, context={'form': form,
                                                            'title': 'Логин',
                                                            'error_text': 'Введён неправильный логин или пароль'})


class LogoutView(View):
    """View для логаута"""

    def get(self, request):
        auth.logout(request)
        return HttpResponseRedirect(reverse('index'))


class RegisterView(CreateView):
    """Страница регистрации пользователя"""
    model = User
    template_name = 'authapp/user_auth/register.html'
    success_url = reverse_lazy('index')
    form_class = UserRegisterForm

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Регистрация'
        return context


class EditView(View):
    """Страница редактирования профиля"""
    model = User
    template_name = 'authapp/users_crud/user_form.html'
    form_class = UserEditForm
    success_url = reverse_lazy('authapp:users_list')

    def get(self, request):
        edit_form = UserEditForm(instance=self.request.user)
        context = {
            'title': 'Редактирование пользователя',
            'edit_form': edit_form,
        }
        return render(self.request, 'authapp/user_auth/edit.html', context)

    def post(self, request, *args, **kwargs):
        edit_form = UserEditForm(request.POST, request.FILES, instance=request.user)
        if edit_form.is_valid():
            edit_form.save()
            return HttpResponseRedirect(reverse('auth:edit'))


class UserCreateView(SuperUserCheck, CreateView):
    """Создание пользователя"""
    model = User
    template_name = 'authapp/users_crud/user_form.html'
    success_url = reverse_lazy('authapp:users_list')
    form_class = UserRegisterForm

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['title'] = 'Создание пользователя'
        return context


class UserListView(SuperUserCheck, ListView):
    """Просмотр всех пользователей"""
    context_object_name = "users"
    model = User
    paginate_by = 6
    template_name = 'authapp/users_crud/users.html'

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['title'] = 'Список пользователей'
        return context


class UserUpdateView(SuperUserCheck, UpdateView):
    """Изменение пользователя"""
    model = User
    template_name = 'authapp/users_crud/user_form.html'
    form_class = UserEditForm
    success_url = reverse_lazy('authapp:users_list')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Редактирование пользователя'
        return context


class UserDeleteView(SuperUserCheck, DeleteView):
    """Удаление пользователя"""
    model = User
    template_name = 'authapp/users_crud/user_delete.html'

    def get_success_url(self):
        return reverse('authapp:users_list')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Удаление пользователя'
        return context
    

class UserCreateAPIView(APIView):
    """API Создание пользователя"""
    def get(self, request):
        item = User.objects.all()
        serializer = UserSerializer(item, many=True)
        return Response(serializer.data)

    def post(self, request):
        serializer = UserSerializer(data=request.data)
        # serializer = UserSerializer(data=request.data, many=True)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)


class UserUpdateAPIView(APIView):
    """API Изменение пользователя"""

    def get_object(self, pk):
        try:
            return User.objects.get(pk=pk)
        except User.DoesNotExist:
            raise Http404

    def get(self, request, pk):
        item = self.get_object(pk)
        serializer = UserSerializer(item)
        return Response(serializer.data)

    def put(self, request, pk):
        item = self.get_object(pk)
        serializer = UserSerializer(item, data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

    def delete(self, request, pk):
        item = self.get_object(pk)
        item.delete()
        return Response(status=status.HTTP_204_NO_CONTENT)

templates/authapp/users_crud/user_delete.html
{% extends 'authapp/base.html' %}

{% block content %}
    <div class="del_block">
        Уверены, что хотите удалить пользователя {{ user.name }}?
        <form method="post">
            {% csrf_token %}
            <input type="submit" class="btn-block btn-danger col-lg-12" value="Да">
        </form>
        <button onclick="document.location='{% url 'authapp:users_list' %}'" class="btn-block btn-success col-lg-12">
            Отмена
        </button>
    </div>
{% endblock %}

templates/authapp/users_crud/user_form.html
{% extends 'base.html' %}

{% block content %}
    <div class="admin_block">
        <a href="{% url 'authapp:users_list' %}" class="admin_cross"></a>
        <form class="form-horizontal" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form }}
{#            {{ user_form.as_p }}#}
{#            {{ profile_form.as_p }}#}
            <input class="auth_button" type="submit" value="Сохранить" class="btn-block btn-primary col-lg-12">
        </form>
    </div>
{% endblock %}

templates/authapp/users_crud/users.html
{% extends 'base.html' %}
{% load static %}
{% load media_tags %}

{% block content %}
    <a class="nav-item nav-link navigation-links add_button" href="{% url 'auth:user_create' %}"><i
            class="fa fa-plus"></i>
        Новый пользователь
    </a>
    <div class="users_list">
        {% for user in users %}
            <div class="container_box
                {% if not user.is_active %}
                    not_active
                {% endif %}
                {% if user.is_superuser %}
                    admin_highlight
                {% endif %}">
                <img class="block_avatar" src="{{ user.avatar|media_for_users }}" alt="{{ user.username }}">
                <div class="user_role">
                    {% if user.is_superuser %}
                        <h4>
                            <span class="text-danger">администратор</span>
                        </h4>
                    {% else %}
                        <h4>
                            пользователь
                        </h4>
                    {% endif %}
                    <br>
                    {{ user.username }}<br>
                    <br>
                    <a class="user_edit_button" href={% url 'authapp:user_update' user.pk %}>
                        редактировать
                    </a>
                    <br>
                    <a class="user_edit_button" href={% url 'authapp:user_delete' user.pk %}>
                        {% if user.is_active %}
                            удалить
                        {% else %}
                            восстановить
                        {% endif %}
                    </a>
                </div>
            </div>
        {% endfor %}

    </div>
    <div class="pagi_div">
        <nav>
            {% if is_paginated %}
                <ul class="pagination">
                    {% if page_obj.has_previous %}
                        <li class="page-item">
                            <a class="page-link" href="?page={{ page_obj.previous_page_number }}">&laquo;</a>
                        </li>
                    {% else %}
                        <li class="page-item disabled">
                            <a class="page-link" href="#">&laquo;</a>
                        </li>
                    {% endif %} {% for i in paginator.page_range %} {% if page_obj.number == i %}
                    <li class="page-item"><a class="page-link active">{{ i }}</a></li>
                {% else %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ i }}">{{ i }}</a>
                    </li>
                {% endif %} {% endfor %} {% if page_obj.has_next %}
                    <li class="page-item">
                        <a href="?page={{ page_obj.next_page_number }}" class="page-link">&raquo;</a>
                    </li>
                {% else %}
                    <li class="page-item disabled">
                        <a class="page-link">&raquo;</a>
                    </li>
                {% endif %}
                </ul>
            {% endif %}
        </nav>
    </div>
{% endblock %}