authapp/urls.py
from django.urls import path
from authapp import views as authapp

app_name = 'authapp'


urlpatterns = [
    path('login/', authapp.LoginView.as_view(), name='login'),
    path('logout/', authapp.LogoutView.as_view(), name='logout'),
    path('register/', authapp.RegisterView.as_view(), name='register'),
    path('edit/', authapp.EditView.as_view(), name='edit'),
    path('users/', authapp.UserListView.as_view(), name='users_list'),
    path('user/create/', authapp.UserCreateView.as_view(), name='user_create'),
    path('user/update/<int:pk>/', authapp.UserUpdateView.as_view(),
         name='user_update'),
    path('user/delete/<int:pk>/', authapp.UserDeleteView.as_view(),
         name='user_delete'),

    path('api/user_create/', authapp.UserCreateAPIView.as_view(), name='api_user_create'),
    path('api/user_update/<int:pk>/', authapp.UserUpdateAPIView.as_view(), name='api_user_update'),
]

bookshelf/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from mainapp import views as mainapp

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('books/', include('bookapp.urls', namespace='books')),
    path('', mainapp.Index.as_view(), name='index'),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/includes/inc_menu.html
<div class="admin_menu">
    <ul>
{#        {% if not 'index' in request.resolver_match.url_name %}#}
        <li><a href="{% url 'index' %}"><i class="fa fa-th"></i>главная</a></li>
{#        {% endif %}#}
        {% if user.is_authenticated %}
            {% if user.is_superuser %}
                <li><a style="color:#ba1b1b" class="log_regedit"
                   href="{% url 'auth:edit' %}"><i class="fa fa-user"></i>администратор:{{ user.username }}</a></li>
                <li><a style="color:#ba1b1b" href="{% url 'auth:users_list' %}"><i class="fa fa-user-circle-o"></i>
                    пользователи</a></li>
            {% else %}
                <li><a  class="log_regedit" href="{% url 'auth:edit' %}"><i class="fa fa-user"></i>
                    редактировать: {{ user.first_name|default:'пользователь' }}</a></li>
            {% endif %}
            <li><a class="log_entexit" href="{% url 'auth:logout' %}"><i class="fa fa-sign-out"></i>
                выйти</a></li>
        {% else %}
            <li><a class="log_entexit" href="{% url 'auth:login' %}"><i class="fa fa-sign-in"></i>
                войти</a></li>
            <li><a class="log_regedit" href="{% url 'auth:register' %}"><i class="fa fa-address-card-o"></i>
                регистрация</a></li>
        {% endif %}

    </ul>
</div>