authapp/urls.py
from django.urls import path
from authapp import views as authapp

app_name = 'authapp'


urlpatterns = [
    path('login/', authapp.LoginView.as_view(), name='login'),
    path('logout/', authapp.LogoutView.as_view(), name='logout'),
    path('register/', authapp.RegisterView.as_view(), name='register'),
    path('edit/', authapp.EditView.as_view(), name='edit'),
    path('users/', authapp.UserListView.as_view(), name='users_list'),
    path('user/create/', authapp.UserCreateView.as_view(), name='user_create'),
    path('user/update/<int:pk>/', authapp.UserUpdateView.as_view(),
         name='user_update'),
    path('user/delete/<int:pk>/', authapp.UserDeleteView.as_view(),
         name='user_delete'),

    path('api/user_create/', authapp.UserCreateAPIView.as_view(), name='api_user_create'),
    path('api/user_update/<int:pk>/', authapp.UserUpdateAPIView.as_view(), name='api_user_update'),
]

bookapp/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from bookapp import views as bookapp

app_name = 'bookapp'

urlpatterns = [
    path('book_create/', bookapp.BookCreateView.as_view(), name='book_create'),
    path('book_read/<pk>/', bookapp.BookDetailView.as_view(), name='book_read'),
    path('book_update/<pk>/', bookapp.BookUpdateView.as_view(), name='book_update'),
    path('book_delete/<pk>/', bookapp.BookDeleteView.as_view(), name='book_delete'),

    path('api/books_create/', bookapp.BookCreateAPIView.as_view(), name='books_create_api'),
    path('api/books_update/<int:pk>/', bookapp.BookUpdateAPIView.as_view(), name='books_update_api'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bookshelf/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from mainapp import views as mainapp

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('books/', include('bookapp.urls', namespace='books')),
    path('', mainapp.Index.as_view(), name='index'),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bookapp/models.py
from django.db import models
from authapp.models import User
from ckeditor.fields import RichTextField

NULLABLE = {'blank': True, 'null': True}


class Books(models.Model):
    """Книги"""
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Автор')
    name = models.CharField(max_length=128, verbose_name='Название книги')
    image = models.ImageField(upload_to='books', blank=True, null=True, verbose_name='Обложка')
    text = RichTextField(verbose_name='Текст книги')
    short_desc = models.CharField(max_length=255, verbose_name='Краткое описание')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.name}'

    class Meta:
        verbose_name = 'Книга'
        verbose_name_plural = 'Книги'

bookapp/forms.py
from django import forms
from bookapp.models import Books


class BookForm(forms.ModelForm):
    class Meta:
        model = Books
        fields = ('name', 'text', 'image', 'short_desc')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''

bookapp/views.py
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy, reverse
from django.utils.decorators import method_decorator
from django.views.generic import CreateView, UpdateView, DeleteView, DetailView
from bookapp.forms import BookForm
from bookapp.models import Books
from mainapp.mixins import BelongsToUserCheck
from django.http import Http404
from rest_framework import status
from rest_framework.response import Response
from rest_framework.views import APIView
from .serializers import BooksSerializer


class BookDetailView(DetailView):
    """Чтение книги"""
    model = Books
    template_name = 'bookapp/book_crud/book_view.html'

    def get_context_data(self, *args, **kwargs):
        book = Books.objects.get(pk=self.kwargs['pk'])
        context = super().get_context_data(**kwargs)
        context['book'] = book
        context['title'] = book.name
        return context


@method_decorator(login_required, name='dispatch')
class BookCreateView(CreateView):
    """Создание книги"""
    model = Books
    template_name = 'bookapp/book_crud/book_form.html'
    success_url = reverse_lazy('index')
    form_class = BookForm

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Создание книги'
        return context

    def post(self, request, *args, **kwargs):
        """Автоматически делаем пользователя сессии автором книги"""
        if request.user.is_authenticated:
            form = self.form_class(request.POST)
            if form.is_valid():
                book = form.save(commit=False)
                book.user = request.user
                book.save()
                return HttpResponseRedirect(reverse("index"))


class BookUpdateView(BelongsToUserCheck, UpdateView):
    """Редактирование книги"""
    model = Books
    template_name = 'bookapp/book_crud/book_form.html'
    form_class = BookForm
    success_url = reverse_lazy('index')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Редактирование книги'
        return context


class BookDeleteView(BelongsToUserCheck, DeleteView):
    """Удаление книги"""
    model = Books
    template_name = 'bookapp/book_crud/book_delete.html'

    def get_success_url(self):
        return reverse('index')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Удаление книги'
        return context


class BookCreateAPIView(APIView):
    """API Создание книги"""
    def get(self, request):
        """Выводит все"""
        mailing = Books.objects.all()
        serializer = BooksSerializer(mailing, many=True)
        return Response(serializer.data)

    def post(self, request):
        serializer = BooksSerializer(data=request.data)
        # serializer = BooksSerializer(data=request.data, many=True)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)


class BookUpdateAPIView(APIView):
    """API измениния книги"""
    def get_object(self, pk):
        try:
            return Books.objects.get(pk=pk)
        except Books.DoesNotExist:
            raise Http404

    def get(self, request, pk):
        book = self.get_object(pk)
        serializer = BooksSerializer(book)
        return Response(serializer.data)

    def put(self, request, pk):
        book = self.get_object(pk)
        serializer = BooksSerializer(book, data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

    def delete(self, request, pk):
        book = self.get_object(pk)
        book.delete()
        return Response(status=status.HTTP_204_NO_CONTENT)

templates/bookapp/book_crud/book_delete.html
{% extends 'base.html' %}

{% block content %}
    <br>
    <br>
    <div class="del_block">
        Уверены, что хотите удалить книгу?
        <form method="post">
            {% csrf_token %}
            <input type="submit" class="btn-block btn-danger col-lg-12" value="Да">
        </form>
        <button onclick="document.location='{% url 'index' %}'" class="btn-block btn-success col-lg-12">
            Отмена
        </button>
    </div>
{% endblock %}

templates/bookapp/book_crud/book_form.html
{% extends 'base.html' %}
{% load crispy_forms_filters %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}
<div class="container post_form">
    <h2>Твоя книга:</h2>
    <div id="img-box"></div>
    <div class="admin_block">
        <form class="form-horizontal" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.media }}
            {{ form|crispy  }}
            <br>
            <input class="auth_button" type="submit" value="Загрузить книгу">
        </form>
    </div>
</div>
{% endblock %}

{% block js_bottom %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/jquery-validation@1.17.0/dist/jquery.validate.js"></script>
    <script src="{% static 'js/book_add.js' %}"></script>
{% endblock %}

templates/bookapp/book_crud/book_view.html
{% extends 'base.html' %}
{% load static %}
{% load media_tags %}

{% block js %}

{% endblock %}

{% block content %}
    {% if book.image %}
        <img class="view_book_img_box" src="/media/{{ book.image }}" alt="book_img">
    {% endif %}
    <div class="container text">
        <br>

        <div style="display: flex">
            {% if user.id == book.user.id or user.is_superuser %}
                <a href="{% url 'books:book_update' book.id %}" class="btn btn-warning">редактировать</a>
                <a href="{% url 'books:book_delete' book.id %}" class="btn btn-danger">удалить</a>
            {% endif %}
        </div>

        <h1>{{ book.name }}</h1>
        <p>{{ book.text|safe }}</p>

        <div>

        </div>

    </div>
{% endblock %}